projectname: yxmsw2007.github.io
username: yxmsw2007
description: yxmsw2007's blog
baseurl: /yxmsw2007.github.io
gems:
- jekyll-sitemap
# markdown: redcarpet
markdown: kramdown 
redcarpet: 
    extensions: ["fenced_code_blocks", "tables"]
#   extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]
safe: false
#pygments: true
highlighter: pygments
title: yxmsw2007
paginate: 9
paginate_path: "page:num"
categories_path: category.html
tags_path: tag.html
