projectname: yxmsw2007.github.io
username: yxmsw2007
description: yxmsw2007's blog
baseurl: /yxmsw2007.github.io
gems:
- jekyll-sitemap
markdown: redcarpet
redcarpet: 
    extensions: ["tables"]
#   extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]
safe: false
#pygments: true
highlighter: pygments
title: yxmsw2007
paginate: 5
paginate_path: "page:num"
