projectname: yxmsw2007.github.io
username: yxmsw2007
baseurl: /yxmsw2007.github.io
markdown: redcarpet
redcarpet: 
    extensions: ["tables"]
#   extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]
safe: false
pygments: true
title: yxmsw2007
